### ISSUE TITLE
UI/UX changes

### ISSUE THREAD

**Issue by abhinav12k** [abhinav78910/MoviFreak#2]
Change the format of tiles showing on the main screen. Include ratings in the tile also. For better understanding see the image below.
![Popcorn-Time-v3 6 6-Mod-Lite](https://user-images.githubusercontent.com/51455561/91544281-21595180-e93d-11ea-9ef7-eadb803763fd.png)

**Comment by animsh** [comment]
Sir, Can I work on this project for hacktoberfest2020?

**Comment by abhinav12k** [comment]
I have assigned the issue to you

**Comment by animsh** [comment]
Thank you sir, can I get the work of notes app too?

**Comment by abhinav12k** [comment]
Sure, but it's easier you can get a good start from here. After fixing issues on this you can get started with that too.

**Comment by animsh** [comment]
Okay sir, how can I contact you? any another medium?

**Comment by abhinav12k** [comment]
You can contact me through telegram https://t.me/abhinav12k . Later we can shift to slack or gitter.
