### ISSUE TITLE
Day and Night Mode

### ISSUE THREAD

**Issue by abhinav12k** [abhinav78910/MoviFreak#3]
Implement Day and Night mode inside the app. User must be able to shift between the dark mode and day mode from the settings as well as the app must be adaptable to system dark mode.

**Comment by animsh** [comment]
Sir, I would like to work on this project for hacktoberfest2020

**Comment by abhinav12k** [comment]
I have assigned the issue to @animsh, you can start working on the issue.
Note - I have been working on java kotlin interop so please also check out the code in the feature branch too. It will give you clear understanding of the code.
